:8080

handle_path /assets/* {
    root * /lila/public
    file_server
    header Cache-Control "max-age=31536000"
}

handle_path /oops/* {
    root * /lila/public/oops
    file_server
}

@websockets {
    header Connection *Upgrade*
    header Upgrade websocket
}

reverse_proxy @websockets localhost:9664 {
    header_up Origin https://chesspuertoricocoffee.com
}

reverse_proxy localhost:9663 {
    header_up Host chesspuertoricocoffee.com
    header_up Origin https://chesspuertoricocoffee.com
    header_down Access-Control-Allow-Origin "*"
}
